# Generated by Django 4.2.2 on 2023-06-07 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0055_alter_video_added_by_alter_video_course_and_more"),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="added_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.teacher",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.subject",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="added_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.teacher",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.subject",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="added_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.teacher",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.subject",
            ),
            preserve_default=False,
        ),
    ]
