# Generated by Django 4.2 on 2023-06-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0055_alter_video_added_by_alter_video_course_and_more'),
        ('quiz', '0003_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subject',
        ),
        migrations.AlterField(
            model_name='category',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_app.hod'),
        ),
    ]
