# Generated by Django 4.2.1 on 2023-06-11 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_remove_category_subject_alter_category_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 6, 11, 16, 10, 15, 825847),
            ),
            preserve_default=False,
        ),
    ]
