# Generated by Django 4.2.2 on 2023-06-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0056_remove_classes_classes_department_and_more'),
        ('quiz', '0005_quiz_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_app.teacher'),
        ),
    ]
