# Generated by Django 4.1.7 on 2023-04-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_profile_pic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
