# Generated by Django 4.1.7 on 2023-04-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0002_remove_hod_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='school_description',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_mission',
            field=models.CharField(default='Good School', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='school_vision',
            field=models.CharField(default='Good School', max_length=200),
            preserve_default=False,
        ),
    ]
