# Generated by Django 4.1.7 on 2023-04-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0003_course_course_description_course_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionyear',
            name='session_name',
            field=models.CharField(default='Feb', max_length=200),
            preserve_default=False,
        ),
    ]
