# Generated by Django 4.1.7 on 2023-04-24 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0004_sessionyear_session_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_app.subject')),
            ],
        ),
    ]
