# Generated by Django 4.1.7 on 2023-04-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(default='mis_tutorial', upload_to='books'),
            preserve_default=False,
        ),
    ]
