# Generated by Django 4.2 on 2023-04-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0006_book_book_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_description",
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
