# Generated by Django 4.2 on 2023-04-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0007_book_book_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_image",
            field=models.ImageField(blank=True, upload_to="books_thumbnails"),
        ),
    ]
