# Generated by Django 4.2 on 2023-04-24 09:22

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0008_book_book_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_title", models.CharField(max_length=200)),
                ("video_description", models.TextField(max_length=1024, null=True)),
                ("video", embed_video.fields.EmbedVideoField()),
                (
                    "video_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning_app.subject",
                    ),
                ),
            ],
        ),
    ]
