# Generated by Django 4.2 on 2023-04-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0010_pastpaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastpaper",
            name="paper",
            field=models.FileField(default="paper", upload_to="pastpapers"),
            preserve_default=False,
        ),
    ]
