# Generated by Django 4.2 on 2023-04-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0011_pastpaper_paper"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastpaper",
            name="paper_title",
            field=models.CharField(default="OOP", max_length=200),
            preserve_default=False,
        ),
    ]
