# Generated by Django 4.2 on 2023-04-25 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0012_pastpaper_paper_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="stud_class",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject_articles",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject_assignments",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject_books",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject_cats",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject_exams",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject_papers",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject_projects",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject_videos",
        ),
        migrations.AddField(
            model_name="course",
            name="course_code",
            field=models.IntegerField(default=303),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="stud_course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="stud_facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="stud_instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="stud_linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="stud_phone",
            field=models.IntegerField(default=12345678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="stud_twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="stud_whatsapp",
            field=models.URLField(blank=True, null=True),
        ),
    ]
