# Generated by Django 4.1.7 on 2023-04-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0013_remove_student_stud_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='exam_subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='pastpaper',
            old_name='paper_subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_subject',
            new_name='subject',
        ),
    ]
