# Generated by Django 4.1.7 on 2023-04-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0015_rename_assignment_course_assignment_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_code', models.IntegerField()),
                ('exam_body', models.PositiveSmallIntegerField(choices=[(1, 'KNEC'), (2, 'KASNEB'), (3, 'Internal')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_be_submitted_by', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_app.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_app.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_app.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
