# Generated by Django 4.1.7 on 2023-04-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0016_examtest_delete_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtest',
            name='exam_file',
            field=models.FileField(blank=True, upload_to='exams'),
        ),
    ]
