# Generated by Django 4.2 on 2023-04-26 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0019_usernotifications_usermessages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermessages",
            old_name="sent_by",
            new_name="sent_to",
        ),
    ]
