# Generated by Django 4.2 on 2023-04-26 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0020_rename_sent_by_usermessages_sent_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermessages",
            name="sent_to",
        ),
        migrations.DeleteModel(
            name="UserNotifications",
        ),
        migrations.DeleteModel(
            name="UserMessages",
        ),
    ]
