# Generated by Django 4.2 on 2023-04-28 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0022_book_date_added_pastpaper_date_added_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examtest",
            options={"get_latest_by": "created_at"},
        ),
    ]
