# Generated by Django 4.2 on 2023-04-28 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0023_alter_examtest_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"get_latest_by": "updated_at"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"get_latest_by": "date_added"},
        ),
        migrations.AlterModelOptions(
            name="examtest",
            options={"get_latest_by": "updated_at"},
        ),
        migrations.AlterModelOptions(
            name="pastpaper",
            options={"get_latest_by": "date_added"},
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"get_latest_by": "date_added"},
        ),
    ]
