# Generated by Django 4.2 on 2023-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0024_alter_assignment_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"get_latest_by": "date_added", "ordering": ["-date_added"]},
        ),
        migrations.AlterField(
            model_name="assignment",
            name="deadline",
            field=models.DateTimeField(),
        ),
    ]
