# Generated by Django 4.2 on 2023-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0025_alter_book_options_alter_assignment_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="examtest",
            old_name="to_be_submitted_by",
            new_name="deadline",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="submitted_at",
        ),
        migrations.RemoveField(
            model_name="examtest",
            name="exam_code",
        ),
        migrations.RemoveField(
            model_name="pastpaper",
            name="paper_code",
        ),
        migrations.AddField(
            model_name="assignment",
            name="assignment_file",
            field=models.FileField(default="ICT", upload_to="assignments"),
            preserve_default=False,
        ),
    ]
