# Generated by Django 4.2 on 2023-04-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0027_assignment_guidelines"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
    ]
