# Generated by Django 4.2 on 2023-04-28 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0028_assignment_submitted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="submitted",
        ),
    ]
