# Generated by Django 4.2 on 2023-05-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0029_remove_assignment_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Teacher'), (3, 'Student')], default=3),
        ),
    ]
