# Generated by Django 4.2 on 2023-05-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0030_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(default='Awesome assignment', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='topic',
            field=models.CharField(default='Data Structures and Algorithms', max_length=200),
            preserve_default=False,
        ),
    ]
