# Generated by Django 4.2 on 2023-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0031_assignment_description_assignment_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='guideline1',
            field=models.CharField(default='Do your own work', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='guideline2',
            field=models.CharField(default='Submit to this email', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='guideline3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assignment',
            name='guideline4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assignment',
            name='guideline5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='guidelines',
            field=models.CharField(choices=[('A', models.CharField(max_length=200)), ('B', models.CharField(max_length=200)), ('C', models.CharField(blank=True, max_length=200)), ('D', models.CharField(blank=True, max_length=200)), ('E', models.CharField(blank=True, max_length=200))], max_length=200),
        ),
    ]
