# Generated by Django 4.2 on 2023-05-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0032_assignment_guideline1_assignment_guideline2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='guidelines',
        ),
    ]
