# Generated by Django 4.2 on 2023-05-12 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0033_remove_assignment_guidelines'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_assignment_file', models.FileField(upload_to='assignment/uploads')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_app.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_app.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_app.student')),
            ],
        ),
    ]
