# Generated by Django 4.2 on 2023-05-12 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0034_assignmentuploads_assignmentscores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentuploads',
            options={'verbose_name_plural': 'Assignment Uploads'},
        ),
        migrations.AddField(
            model_name='assignmentuploads',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentuploads',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
