# Generated by Django 4.2 on 2023-05-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0037_alter_assignmentscores_options_pastassignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_uploaded',
        ),
    ]
