# Generated by Django 4.2 on 2023-05-13 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0038_remove_assignment_is_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentscores',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
