# Generated by Django 4.2 on 2023-05-31 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0039_alter_assignmentscores_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentscores',
            name='scored_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearning_app.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentscores',
            name='upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearning_app.assignmentuploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Teacher'), (3, 'Student'), (4, 'HOD')], default=3),
        ),
    ]
