# Generated by Django 4.2 on 2023-05-31 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0041_assignmentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearning_app.assignmentcategory'),
            preserve_default=False,
        ),
    ]
