# Generated by Django 4.2.1 on 2023-06-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0044_course_date_created_subject_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="added_by",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.teacher",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pastpaper",
            name="added_by",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.teacher",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="added_by",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.teacher",
            ),
            preserve_default=False,
        ),
    ]
