# Generated by Django 4.2.1 on 2023-06-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0045_book_added_by_pastpaper_added_by_video_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="module",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Module One"), (2, "Module Two"), (3, "Module Three")],
                default=1,
            ),
        ),
    ]
