# Generated by Django 4.2.1 on 2023-06-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0046_subject_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=200)),
                ("module_description", models.TextField(max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="subject",
            name="module",
        ),
    ]
