# Generated by Django 4.2.1 on 2023-06-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0048_subject_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="subject_description",
            field=models.TextField(default="A very good subject", max_length=1024),
            preserve_default=False,
        ),
    ]
