# Generated by Django 4.2.1 on 2023-06-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0049_subject_subject_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="course",
        ),
        migrations.AddField(
            model_name="teacher",
            name="course",
            field=models.ManyToManyField(to="elearning_app.course"),
        ),
    ]
