# Generated by Django 4.2.1 on 2023-06-03 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0050_remove_teacher_course_teacher_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.department",
            ),
            preserve_default=False,
        ),
    ]
