# Generated by Django 4.2.1 on 2023-06-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0052_teacher_teacher_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="hod",
            name="hod_phone",
            field=models.IntegerField(default=232445667),
            preserve_default=False,
        ),
    ]
