# Generated by Django 4.2.1 on 2023-06-05 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0053_hod_hod_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="deadline",
        ),
        migrations.AddField(
            model_name="assignment",
            name="deadline_date",
            field=models.DateField(
                default=datetime.date(2023, 6, 5)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="deadline_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 6, 5, 19, 58, 26, 643467)
            ),
            preserve_default=False,
        ),
    ]
