# Generated by Django 4.2.1 on 2023-06-06 20:50

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "elearning_app",
            "0054_remove_assignment_deadline_assignment_deadline_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="added_by",
            field=models.ForeignKey(
                help_text="Select the teacher who added the video",
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="course",
            field=models.ForeignKey(
                help_text="Select the course the video belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.course",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Enter the date the video was added"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="subject",
            field=models.ForeignKey(
                help_text="Select the subject the video belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning_app.subject",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=embed_video.fields.EmbedVideoField(help_text="Enter the video link"),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_description",
            field=models.TextField(
                help_text="Enter a short description of the video",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_title",
            field=models.CharField(
                help_text="Enter the title of the video", max_length=200
            ),
        ),
    ]
