# Generated by Django 4.2.2 on 2023-06-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0055_alter_video_added_by_alter_video_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='classes_department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hod',
        ),
        migrations.RemoveField(
            model_name='examtest',
            name='course',
        ),
        migrations.RemoveField(
            model_name='examtest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='examtest',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='school',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='user',
        ),
        migrations.DeleteModel(
            name='SessionYear',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_school',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='module',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Teacher'), (3, 'Student')], default=3),
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='ExamTest',
        ),
    ]
