# Generated by Django 4.2.2 on 2023-06-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_category_added_by'),
        ('elearning_app', '0056_remove_classes_classes_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HOD',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
