# Generated by Django 4.2.2 on 2023-06-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0057_delete_hod_delete_module_delete_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stud_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Teacher'), (3, 'Student')], default=3),
        ),
    ]
