# Generated by Django 4.2.2 on 2023-06-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0058_remove_student_stud_email_remove_student_stud_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_name',
        ),
    ]
